# Generated by Django 2.2.7 on 2019-11-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20191120_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score_sum',
            field=models.FloatField(default=0),
        ),
    ]
