# Generated by Django 2.2.7 on 2019-11-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20191120_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score_avg',
            field=models.FloatField(default=0),
        ),
    ]
